[en]
languageName = "English"
contentDir = "content/en"
weight = 10
[en.params]
languageISO = "EN"
languageTag = "en-US"
footer = 'Made with ❤️ at the <a href="https://utwente.nl">University of Twente</a>'
