name: Build & deploy

on:
  workflow_dispatch:
  push:
    branches:
      - "*"

permissions:
  pages: write
  id-token: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v12
      - name: Enable Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@v7
      - name: Install Dependencies
        run: nix develop --command npm ci
      - name: Build website
        run: nix develop --command npm run build
      - name: Upload static files as artifact
        uses: actions/upload-pages-artifact@v3
        with:
          name: static-files
          path: build/

  publish:
    name: Publish
    needs:
      - build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Deploy to Github Pages
        uses: actions/deploy-pages@v4
        with:
          artifact_name: static-files
